// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CreateWordTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createWord() {
    driver.get("http://localhost:5173/");
    driver.manage().window().setSize(new Dimension(1432, 1032));
    driver.findElement(By.linkText("Wörter erstellen")).click();
    driver.findElement(By.id("word")).click();
    driver.findElement(By.cssSelector("form")).click();
    driver.findElement(By.cssSelector(".form-control")).click();
    driver.findElement(By.id("word")).click();
    driver.findElement(By.id("word")).sendKeys("Banane");
    driver.findElement(By.cssSelector(".add-button")).click();
    assertThat(driver.switchTo().alert().getText(), is("Wort \"Banane\" erfolgreich hinzugefügt!"));
  }
}
